# Generated by Django 3.2.4 on 2021-06-10 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bank_accounts',
            field=models.ManyToManyField(blank=True, null=True, to='company.BankAccount'),
        ),
    ]
