# Generated by Django 3.2.3 on 2021-06-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ammount',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
