# Generated by Django 3.2.3 on 2021-06-03 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cost_center', '0001_initial'),
        ('finance_register', '0002_ammount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammount',
            name='cost_center_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cost_center.costcenter'),
        ),
    ]
