# Generated by Django 3.2.3 on 2021-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_register', '0003_alter_ammount_cost_center_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammount',
            name='finance_register',
        ),
        migrations.AddField(
            model_name='register',
            name='ammounts',
            field=models.ManyToManyField(to='finance_register.Ammount'),
        ),
    ]
